import {StyleSheet} from 'react-native';
import {pallete} from './Colors';
import {fontFamilyTypes} from './type';

const fontFamily: fontFamilyTypes = {
  Medium: '400',
  Regular: '400',
  Bold: '700',
  SemiBold: '700',
};

export const Typo = (
  color?: string | null,
  fontSize?: number | null,
  lineHeight?: number | null,
  fontWeight?: fontFamilyTypes['Bold'] | null,
  align?: 'center' | 'left' | 'right',
) =>
  StyleSheet.create({
    h1: {
      flexWrap: 'wrap',
      textAlign: align || 'left',
      fontSize: fontSize || 40,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      letterSpacing: -1,
      lineHeight: lineHeight || 48,
      fontFamily: 'Epilogue-Italic-VariableFont_wght',
    },
    h2: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 32,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      letterSpacing: -1,
      lineHeight: lineHeight || 38.4,
      fontFamily: 'Epilogue-Italic-VariableFont_wght',
    },
    h3: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 28,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      letterSpacing: -1,
      lineHeight: lineHeight || 33.6,
    },
    h4: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 24,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      // letterSpacing: -5,
      lineHeight: lineHeight || 28.8,
    },
    h5: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 22,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      lineHeight: lineHeight || 26.4,
    },
    h6: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 20,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      letterSpacing: -5,
      lineHeight: lineHeight || 24,
    },
    P1: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 16,
      fontWeight: fontWeight || fontFamily.Regular,
      color: color || pallete.text,
      lineHeight: lineHeight || 24,
    },
    P2: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 14,
      fontWeight: fontWeight || fontFamily.Regular,
      color: color || pallete.text,
      lineHeight: lineHeight || 21,
    },
    P3: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 16,
      fontWeight: fontWeight || fontFamily.SemiBold,
      color: color || pallete.text,
      lineHeight: lineHeight || 24,
    },
    P4: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 14,
      fontWeight: fontWeight || fontFamily.SemiBold,
      color: color || pallete.text,
      lineHeight: lineHeight || 21,
    },
    P5: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 14,
      fontWeight: fontWeight || fontFamily.SemiBold,
      color: color || pallete.text,
      lineHeight: lineHeight || 21,
    },
    P6: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 14,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      lineHeight: lineHeight || 18,
    },
    Caption: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 12,
      fontWeight: fontWeight || fontFamily.Medium,
      color: color || pallete.text,
      lineHeight: lineHeight || 18,
    },
    empty: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 14,
      fontWeight: fontWeight || fontFamily.Medium,
      color: color || pallete.text,
      lineHeight: lineHeight || 18,
    },
    Caption2: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 10,
      fontWeight: fontWeight || fontFamily.SemiBold,
      color: color || pallete.text,
      lineHeight: lineHeight || 10,
    },
    Caption3: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 10,
      fontWeight: fontWeight || fontFamily.Medium,
      color: color || pallete.text,
      lineHeight: lineHeight || 10,
    },
    Nav: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 12,
      fontWeight: fontWeight || fontFamily.Medium,
      color: color || pallete.text,
      lineHeight: lineHeight || 12,
    },
    Button: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 16,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      lineHeight: lineHeight || 28,
    },
    Button2: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 12,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      lineHeight: lineHeight || 18,
    },
    Button3: {
      flexWrap: 'wrap',
      textAlign: align,
      fontSize: fontSize || 10,
      fontWeight: fontWeight || fontFamily.Bold,
      color: color || pallete.text,
      lineHeight: lineHeight || 12,
    },
  });
